apiVersion: v1
kind: Pod

metadata: 
  name: mymultidpod
  labels: 
    newlable: daksh

spec:
  containers: 
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      env: 
        - name: myname
          value: Raghu
        - name: city
          value: Bangalore
      args: ["sleep","100"]
    - name: secondcontainer
      image: coolgourav147/nginx-custom
  initContainers:
    - name: initcontainer
      image: coolgourav147/nginx-custom
      env: 
        - name: myname
          value: Raghu
        - name: city
          value: Bangalore
      args: ["sleep","130"]
