apiVersion: v1
kind: Pod

metadata: 
  name: clusterip
  labels: 
    env: dev
    newlable: daksh

spec:
  containers: 
    - name: containername
      image: coolgourav147/nginx-custom
      ports:
      - protocol: TCP
        port: 8000
        targetPort: 80