apiVersion: v1
kind: Pod

metadata: 
  name: clusterip
  labels: 
    env: dev
    newlable: daksh

spec:
  containers: 
    - name: containername
      image: coolgourav147/nginx-custom
      ports:
      - naem: my ports expose
        protocol: TCP
        containerPort: 8000
        port: 80