apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: myapp2
    type: frontend
spec:
  containers:
      - name: myapp-container
        image: coolgourav147/nginx-custom
        
        