apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: firstset
  labels: 
    name: firstset

spec:
  replicas: 2
  selector:
    matchExpressions:
     - key: app
       operator: In
       values: 
        - myapp1
        - myapp2
  template:
    metadata: 
      name: pod
      labels: 
       app: myapp1
    spec:
      containers: 
      - name: container
        image: raghuveer125/raghuveer125
