apiVersion: apps/v1
kind: Deployment

metadata:
  name: firstdeploy
  labels: 
    name: firstdeploy

spec:
  replicas: 10
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: mydapp
  template:
    metadata: 
      name: dpod
      labels: 
       app: mydapp
    spec:
      containers: 
      - name: container
        image: raghuveer125/raghuveer125
