apiVersion: v1
kind: ReplicationController

metadata:
  name: firstrc
  labels: 
    name: firstrc

spec:
  replicas: 2
  selector:
    app: myapp
  template:
    metadata: 
      name: pod
      labels: 
       app: myapp
    spec:
      containers: 
      - name: container
        image: raghuveer125/raghuveer125
