apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: firstset
  labels: 
    name: firstset

spec:
  replicas: 2
  selector:
    matchLabels:
     app: myapp
  template:
    metadata: 
      name: pod
      labels: 
       app: myapp
    spec:
      containers: 
      - name: container
        image: coolgourav147/nginx-custom
