apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: myapp
    type: frontend
spec:
  containers:
      - name: myapp-container
        image: coolgourav147/nginx-custom
        resources:
          requests:
            memory: 200M

        