apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: myapp
    type: frontend
spec:
  containers:
      - name: myapp-container
        image: raghuveer125/raghuveer125
        resources:
          requests:
            memory: 200M
            cpu: 100m # or .01

        