apiVersion: v1
kind: ReplicationController

metadata:
  name: firstreplicaitoncontoller
  labels: 
    appname: voatingapp

spec:
  replicas: 5
  template:
    metadata: 
      name: myfirstpod
      labels: 
        env: dev
        newlable: daksh

  spec:
    containers: 
    - name: firstcontroller
      image: coolgourav147/nginx-custom
