apiVersion: v1
kind: ReplicationController

metadata:
  name: firstreplicaitoncontroller
  labels: 
    appname: voatingapp

spec:
  replicas: 5
  template:
    metadata: 
      name: myfirstpod
      labels: 
       type: app

    spec:
      containers: 
      - name: firstcontroller
        image: coolgourav147/nginx-custom
